### ISSUE TITLE
Feature request: Add a "latest" release

### ISSUE THREAD

**Issue by carlosperate** [fiam/arm-none-eabi-gcc#25]
To always grab the latest GCC version available in the action:

```yml
steps:
- uses: fiam/arm-none-eabi-gcc@v1
  with:
    release: 'latest'
```

Will be useful for CI workflows that are running tests with multiple GCC versions, to catch issues with the latest version without having to manually check if there has been a release.
Also useful for people that just want to build with the latest no matter what that is.

I'll be happy to provide a PR, just let me know :)
