### ISSUE TITLE
Feature request: add option to use a known install path, for caching

### ISSUE THREAD

**Issue by mikevoyt** [fiam/arm-none-eabi-gcc#29]
Presently, the toolchain gets installed into what appears to be a random path on each invocation; e.g.:
```
extracting to /tmp/tmp-1465uzgsmT2PSR9x/gcc-10-2020-q4
adding /tmp/tmp-1465uzgsmT2PSR9x/gcc-10-2020-q4/bin to PATH
```

However, in order to leverage the [GitHub Actions caching feature](https://docs.github.com/en/actions/advanced-guides/caching-dependencies-to-speed-up-workflows), a known path is required.  I suppose the toolchain could be copied into a known path, but doing so would require finding the path the toolchain was extracted to first (perhaps by parsing `PATH`), then copying it.  

A great feature out of the box would be to allow one to specify the install path via a `with` option, e.g.:

```
steps:
- name: arm-none-eabi-gcc
- uses: fiam/arm-none-eabi-gcc@v1
  with:
    release: '9-2019-q4'
    path: /usr/local/
- run: ...
```
